{{- if .Values.HPA.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "drupal.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.applicationKind }}
    name: {{ template "drupal.fullname" . }}
  minReplicas: {{ .Values.HPA.minReplicas }}
  maxReplicas: {{ .Values.HPA.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.HPA.targetCPUUtilizationPercentage }}
{{- end }}
